---
- name: Execute nvidia-smi command
  hosts: my_vast_ai_host
  tasks:
    - name: Run nvidia_smi command
      command: nvidia-smi
      register: nvidia_smi_output

    - name: Print nvidia_smi command output
      debug:
        var: nvidia_smi_output.stdout
