---
- name: Execute nvidia-smi command
  hosts: my_vast_ai_host
  tasks:
    - name: Run nvidia-smi command
      command: nvidia-smi
      register: nvidia-smi_output

    - name: Print nvidia-smi command output
      debug:
        var: nvidia-smi_output.stdout
